=== xanderjl/www/schemas/work-history-schema.json
{
  "$ref": "#/definitions/workHistorySchema",
  "definitions": {
    "workHistorySchema": {
      "type": "object",
      "properties": {
        "client": {
          "type": "string",
          "minLength": 1
        },
        "endDate": {
          "type": "string"
        },
        "responsibilities": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "role": {
          "type": "string",
          "minLength": 1
        },
        "startDate": {
          "type": "string"
        }
      },
      "required": [
        "client",
        "endDate",
        "responsibilities",
        "role",
        "startDate"
      ],
      "additionalProperties": false
    }
  },
  "$schema": "http://json-schema.org/draft-07/schema#"
}

=== xanderjl/www/src/content/work-history/apollo-graphql-contracted-web-dev.json
{
  "client": "Apollo GraphQL",
  "role": "Conteacted Web Developer",
  "startDate": "2022-01-01",
  "endDate": "2022-04-01",
  "responsibilities": [
    "Drove a full site migration from Gatsby v2 to v4",
    "Implemented a new editing experience in their existing CMS of choice for their marketing team",
    "Started the push to refactor new modules of the site to use TypeScript wherever applicable"
  ]
}

=== xanderjl/www/src/content/work-history/strangelove-senior-web-dev.json
{
  "client": "Strangelove Labs",
  "role": "Senior Web Developer",
  "startDate": "2021-07-01",
  "endDate": "2023-04-01",
  "responsibilities": [
    "Utilized modern web technologies to optimize for maintainability and accelerated development for both internal and client projects.",
    "Directed client consultations regarding feature implementation and technical feasibility on a regular basis."
  ]
}

=== xanderjl/www/src/content/work-history/strangelove-jr-software-engineering-manager.json
{
  "client": "Strangelove Labs",
  "role": "Jr. Software Engineering Manager",
  "startDate": "2023-04-01",
  "endDate": "2023-07-25",
  "responsibilities": [
    "Helped shape development cycle as company matured and the frontend team expanded to include multiple folks and projects",
    "Helped drive an annual review format forward alongside our Chief of Staff"
  ]
}

=== xanderjl/www/src/content/work-history/strangelove-software-engineering-manager.json
{
  "client": "Strangelove Labs",
  "role": "Software Engineering Manager",
  "startDate": "2023-04-01",
  "endDate": "2023-07-25",
  "responsibilities": [
    "Introduced and executed the Shape Up methodology in alignment with the Head of Product, enabling streamlined project management as the company scaled and diversified its project portfolio.",
    "Spearheaded the advancement of the annual review format in collaboration with the Chief of Staff, enhancing the company's approach to performance evaluation and development."
  ]
}
